### ISSUE TITLE
hbase的bytes做为long存储方式，负数比较时是否有问题。

### ISSUE THREAD

**Issue by zhang-xzhi** [alibaba/simplehbase#2]

**Comment by zhang-xzhi** [comment]
写代码验证过了，果然是有问题的。

**Comment by august0715** [comment]
按照字典序，byte从小到大的顺序是：{0,1,2,.....126,127,-128,-127......,-3,-2,-1}。short、int、long也是类似的。如果要让它们实际正确有序，必须要做高位异或运算。
比如：
public static byte[] toBinaryComparableBytes(long v) {
        byte[] b = new byte[8];
        b[0] = (byte) ((v >> 56) ^ 0x80);
        b[1] = (byte) (v >> 48);
        b[2] = (byte) (v >> 40);
        b[3] = (byte) (v >> 32);
        b[4] = (byte) (v >> 24);
        b[5] = (byte) (v >> 16);
        b[6] = (byte) (v >> 8);
        b[7] = (byte) v;
        return b;
    }

这样得到的字节数组的字典序和按照实际大小比较的顺序就是一直了。
反转的函数如下：
public static long fromBinaryComparableBytes(byte[] bytes) {
        byte b = bytes[0];
        long v = b ^ 0x80;
        for (int i = 1; i < 8; i++) {
            b = bytes[i];
            v = (v << 8) + (b & 0xff);
        }
        return v;
    }

在phenix中，byte、short、int、long都是做了这样的处理的！作者也可以考虑下。不过会导致版本不兼容。以前的数据读出来显示的都是错误的。

**Comment by zhang-xzhi** [comment]
是这样的。

只是目前我接触到的应用都是保存>=0的数据的，没有保存负数的场景。
后续我的计划是如果有需要，用cp实现这个转换。

但是目前主要有2个顾虑。
1 不想过早侵入hbase。
2 没有应用场景。

因此没有开始实现这个功能点。

**Comment by zhaiyuyong** [comment]
hbase的bytes做为long存储方式，负数比较时是否有问题。写代码验证过了，果然是有问题的。代码能给看看么？负数比较是指的什么比较？

**Comment by zhang-xzhi** [comment]
TestSpecial

```
@Test
public void cannotHandleNegative() {
    putSlim("id=0,age=100");
    putSlim("id=1,age=0");
    putSlim("id=2,age=-100");

    addHql("select where age greaterequal \"0\"");
    List<MyRecord> myRecordList = simpleHbaseClient.findObjectList(
            new MyRecordRowKey(0), new MyRecordRowKey(100), MyRecord.class,
            TestHqlId, null);
    //should be 2, but result is 3.
    Assert.assertTrue(myRecordList.size() == 3);
}
```
