### ISSUE TITLE
如何支持多个实体？

### ISSUE THREAD

**Issue by yang040840219** [alibaba/simplehbase#8]

**Comment by zhang-xzhi** [comment]
你这里的多个实体是什么意思？

**Comment by yang040840219** [comment]
Person 是一个需要定义配置文件，如果再有另外一个，还可以支持么？

发件人: noreply@github.com [mailto:noreply@github.com] 代表 zhang_xzhi
发送时间: 2014年1月12日 21:42
收件人: zhang-xzhi/simplehbase
抄送: ming-tian
主题: Re: [simplehbase] 如何支持多个实体？ (#8)

你这里的多个实体是什么意思？

**Comment by zhang-xzhi** [comment]
每个client只能操作1个htable。
DO在操作的时候可以使用任意的client。

就是说，你可以只定义一个Person DO。
配置2个client，每个client配置不同的htable。

例如：
2个htable t1,t2.
配置2个client client_A, client_B。
一个DO
可以使用client_A操作DO，数据保存在t1中。
同时可以使用client_B操作DO，数据保存在t2中。

**Comment by zhang-xzhi** [comment]
同时，也支持多个DO共用一个client。

例如：
htable: a, b ,c ,d
可以定义一个client。
3个DO 
DO_A : a
DO_B : a,b,c
DO_C:  a,b,c,d
3个DO都可以使用这个client。
